table 'Hoja 1'
	lineageTag: 32cb57f4-ab78-4b0c-ab09-4cbfeef4e8aa

	column Region
		dataType: string
		lineageTag: 7aa66685-b506-4f5f-862e-c5449eb5ebe7
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Producto
		dataType: string
		lineageTag: 3fe0428e-2ec3-4e03-9458-a8a3e7907809
		summarizeBy: none
		sourceColumn: Producto

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: string
		lineageTag: 71b9125f-897d-4562-a1f3-499e4aa0e6d2
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column Ventas
		dataType: int64
		formatString: #,0
		lineageTag: dec763a8-d9f3-4ee3-9c79-8724613fcf1e
		summarizeBy: sum
		sourceColumn: Ventas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	partition 'Hoja 1-84249273-a59f-4d8d-9577-62184f7faef6' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Admin\Desktop\Curso Excel-PowerBI\Power BI - Practica 1\Ventas.xlsx"), null, true),
				    #"Hoja 1_Sheet" = Source{[Item="Hoja 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Hoja 1_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Region", type text}, {"Producto", type text}, {"Vendedor", type text}, {"Ventas", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

