table T_ID_CAPACIDAD
	lineageTag: e8db4289-848c-4960-a49e-08bfb22108ac

	column ID_CAPACIDAD
		dataType: int64
		formatString: 0
		lineageTag: de28a0a9-8269-417e-bafb-5317a6e1f7d5
		summarizeBy: none
		sourceColumn: ID_CAPACIDAD

		annotation SummarizationSetBy = Automatic

	column DESCRIPCION
		dataType: string
		lineageTag: cc83eee1-635b-4c2e-a7a8-ef12d7643a72
		summarizeBy: none
		sourceColumn: DESCRIPCION
		sortByColumn: ID_CAPACIDAD

		annotation SummarizationSetBy = Automatic

	column 'CANTIDAD LITROS'
		dataType: int64
		formatString: 0
		lineageTag: 5e2d2fc4-d111-4739-830b-2a59fc23b6b7
		summarizeBy: none
		sourceColumn: CANTIDAD LITROS

		annotation SummarizationSetBy = Automatic

	partition T_ID_CAPACIDAD-3bb61e2f-5be2-4fc9-9d8d-c5dc6a995345 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\dlucc\Desktop\Proyectos Power BI\Heladeria\Heladeria_Data.xlsx"), null, true),
				    T_ID_CAPACIDAD_Table = Source{[Item="T_ID_CAPACIDAD",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(T_ID_CAPACIDAD_Table,{{"ID_CAPACIDAD", Int64.Type}, {"DESCRIPCION", type text}}),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Changed Type", "Text Before Delimiter", each Text.BeforeDelimiter([DESCRIPCION], " "), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "CANTIDAD LITROS"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"CANTIDAD LITROS", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

